# create a docker compose with a mongo service. The volume must be mapped to an external volume
version: '3.1'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
