services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    command: -c config_file=/etc/postgresql.conf
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
    volumes:
      - ./deploy/postgresql.conf:/etc/postgresql.conf
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - '6379:6379'

  proxy:
    build: https://github.com/gittrends-app/github-proxy-server.git
    restart: unless-stopped
    command: --tokens /tokens.txt
    environment:
      PORT: 80
      GPS_REQUEST_TIMEOUT: ${GPS_REQUEST_TIMEOUT:-15000}
      GPS_MIN_REMAINING: ${GPS_MIN_REMAINING:-100}
    ports:
      - 3000:80
    volumes:
      - ./${TOKENS_FILE:-tokens.txt}:/tokens.txt:ro

volumes:
  pgdata:
