import { describe, expect, it } from '@jest/globals';
import { repositorySchema } from './repository';

describe('Repository entity', () => {
  const baseFields = {
    id: 28457823,
    node_id: 'MDEwOlJlcG9zaXRvcnkyODQ1NzgyMw==',
    name: 'freeCodeCamp',
    full_name: 'freeCodeCamp/freeCodeCamp',
    private: false,
    owner: {
      login: 'freeCodeCamp',
      id: 9892522,
      node_id: 'MDEyOk9yZ2FuaXphdGlvbjk4OTI1MjI=',
      avatar_url: 'https://avatars.githubusercontent.com/u/9892522?v=4',
      url: 'https://api.github.com/users/freeCodeCamp',
      type: 'User',
      site_admin: false
    },
    forks_count: 36168,
    stargazers_count: 393343,
    watchers_count: 393343,
    size: 449097,
    default_branch: 'main',
    open_issues_count: 233,
    has_issues: true,
    has_projects: true,
    has_wiki: true,
    has_pages: false,
    has_discussions: false,
    archived: false,
    disabled: false,
    pushed_at: '2024-07-10T10:06:44Z',
    created_at: '2014-12-24T17:49:19Z',
    updated_at: '2024-07-10T11:17:48Z',
    forks: 36168,
    open_issues: 233,
    watchers: 393343
  };

  it('should validate required fields', () => {
    expect(() => repositorySchema.parse(baseFields)).not.toThrowError();
    for (const key of Object.keys(baseFields)) {
      expect(() => repositorySchema.parse({ ...baseFields, [key]: undefined })).toThrowError();
    }
  });

  it('should remove null fields', () => {
    const result = repositorySchema.parse({ ...baseFields, description: null });
    expect(result).not.toHaveProperty('bio');
  });

  it('should remove empty strings', () => {
    const result = repositorySchema.parse({ ...baseFields, homepage: '' });
    expect(result).not.toHaveProperty('homepage');
  });

  it('should add __typename and __obtained_at to user', () => {
    const result = repositorySchema.parse(baseFields);
    expect(result).toHaveProperty('__typename', 'Repository');
    expect(result).toHaveProperty('__obtained_at', expect.any(Date));
  });

  it('should parse repository from search', () => {
    const repository = {
      id: 28457823,
      node_id: 'MDEwOlJlcG9zaXRvcnkyODQ1NzgyMw==',
      name: 'freeCodeCamp',
      full_name: 'freeCodeCamp/freeCodeCamp',
      private: false,
      owner: {
        login: 'freeCodeCamp',
        id: 9892522,
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjk4OTI1MjI=',
        avatar_url: 'https://avatars.githubusercontent.com/u/9892522?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/freeCodeCamp',
        html_url: 'https://github.com/freeCodeCamp',
        followers_url: 'https://api.github.com/users/freeCodeCamp/followers',
        following_url: 'https://api.github.com/users/freeCodeCamp/following{/other_user}',
        gists_url: 'https://api.github.com/users/freeCodeCamp/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/freeCodeCamp/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/freeCodeCamp/subscriptions',
        organizations_url: 'https://api.github.com/users/freeCodeCamp/orgs',
        repos_url: 'https://api.github.com/users/freeCodeCamp/repos',
        events_url: 'https://api.github.com/users/freeCodeCamp/events{/privacy}',
        received_events_url: 'https://api.github.com/users/freeCodeCamp/received_events',
        type: 'Organization',
        site_admin: false
      },
      html_url: 'https://github.com/freeCodeCamp/freeCodeCamp',
      description:
        "freeCodeCamp.org's open-source codebase and curriculum. Learn to code for free.",
      fork: false,
      url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp',
      forks_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/forks',
      keys_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/keys{/key_id}',
      collaborators_url:
        'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/teams',
      hooks_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/hooks',
      issue_events_url:
        'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/issues/events{/number}',
      events_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/events',
      assignees_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/assignees{/user}',
      branches_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/branches{/branch}',
      tags_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/tags',
      blobs_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/languages',
      stargazers_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/stargazers',
      contributors_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/contributors',
      subscribers_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/subscribers',
      subscription_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/subscription',
      commits_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/comments{/number}',
      issue_comment_url:
        'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/contents/{+path}',
      compare_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/merges',
      archive_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/downloads',
      issues_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/issues{/number}',
      pulls_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/labels{/name}',
      releases_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/releases{/id}',
      deployments_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/deployments',
      created_at: '2014-12-24T17:49:19Z',
      updated_at: '2024-07-10T11:17:48Z',
      pushed_at: '2024-07-10T10:06:44Z',
      git_url: 'git://github.com/freeCodeCamp/freeCodeCamp.git',
      ssh_url: 'git@github.com:freeCodeCamp/freeCodeCamp.git',
      clone_url: 'https://github.com/freeCodeCamp/freeCodeCamp.git',
      svn_url: 'https://github.com/freeCodeCamp/freeCodeCamp',
      homepage: 'http://contribute.freecodecamp.org/intro',
      size: 449097,
      stargazers_count: 393343,
      watchers_count: 393343,
      language: 'TypeScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: false,
      has_pages: false,
      has_discussions: false,
      forks_count: 36168,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 233,
      license: {
        key: 'bsd-3-clause',
        name: 'BSD 3-Clause "New" or "Revised" License',
        spdx_id: 'BSD-3-Clause',
        url: 'https://api.github.com/licenses/bsd-3-clause',
        node_id: 'MDc6TGljZW5zZTU='
      },
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [
        'careers',
        'certification',
        'community',
        'curriculum',
        'd3',
        'education',
        'freecodecamp',
        'hacktoberfest',
        'javascript',
        'learn-to-code',
        'math',
        'nodejs',
        'nonprofits',
        'programming',
        'react',
        'teachers'
      ],
      visibility: 'public',
      forks: 36168,
      open_issues: 233,
      watchers: 393343,
      default_branch: 'main',
      permissions: {
        admin: false,
        maintain: false,
        push: false,
        triage: false,
        pull: true
      },
      score: 1.0,
      text_matches: []
    };

    expect(repositorySchema.parse(repository)).toEqual({
      id: 28457823,
      node_id: 'MDEwOlJlcG9zaXRvcnkyODQ1NzgyMw==',
      name: 'freeCodeCamp',
      full_name: 'freeCodeCamp/freeCodeCamp',
      private: false,
      owner: expect.objectContaining({ login: 'freeCodeCamp', id: 9892522 }),
      description:
        "freeCodeCamp.org's open-source codebase and curriculum. Learn to code for free.",
      fork: false,
      url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp',
      created_at: new Date('2014-12-24T17:49:19Z'),
      updated_at: new Date('2024-07-10T11:17:48Z'),
      pushed_at: new Date('2024-07-10T10:06:44Z'),
      homepage: 'http://contribute.freecodecamp.org/intro',
      size: 449097,
      stargazers_count: 393343,
      watchers_count: 393343,
      language: 'TypeScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: false,
      has_pages: false,
      has_discussions: false,
      forks_count: 36168,
      archived: false,
      disabled: false,
      open_issues_count: 233,
      license: 'bsd-3-clause',
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [
        'careers',
        'certification',
        'community',
        'curriculum',
        'd3',
        'education',
        'freecodecamp',
        'hacktoberfest',
        'javascript',
        'learn-to-code',
        'math',
        'nodejs',
        'nonprofits',
        'programming',
        'react',
        'teachers'
      ],
      visibility: 'public',
      forks: 36168,
      open_issues: 233,
      watchers: 393343,
      default_branch: 'main',
      __typename: 'Repository',
      __obtained_at: expect.any(Date)
    });
  });

  it('should parse full repository', () => {
    const repository = {
      id: 2126244,
      node_id: 'MDEwOlJlcG9zaXRvcnkyMTI2MjQ0',
      name: 'bootstrap',
      full_name: 'twbs/bootstrap',
      private: false,
      owner: {
        login: 'twbs',
        id: 2918581,
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjI5MTg1ODE=',
        avatar_url: 'https://avatars.githubusercontent.com/u/2918581?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/twbs',
        html_url: 'https://github.com/twbs',
        followers_url: 'https://api.github.com/users/twbs/followers',
        following_url: 'https://api.github.com/users/twbs/following{/other_user}',
        gists_url: 'https://api.github.com/users/twbs/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/twbs/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/twbs/subscriptions',
        organizations_url: 'https://api.github.com/users/twbs/orgs',
        repos_url: 'https://api.github.com/users/twbs/repos',
        events_url: 'https://api.github.com/users/twbs/events{/privacy}',
        received_events_url: 'https://api.github.com/users/twbs/received_events',
        type: 'Organization',
        site_admin: false
      },
      html_url: 'https://github.com/twbs/bootstrap',
      description:
        'The most popular HTML, CSS, and JavaScript framework for developing responsive, mobile first projects on the web.',
      fork: false,
      url: 'https://api.github.com/repos/twbs/bootstrap',
      forks_url: 'https://api.github.com/repos/twbs/bootstrap/forks',
      keys_url: 'https://api.github.com/repos/twbs/bootstrap/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/twbs/bootstrap/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/twbs/bootstrap/teams',
      hooks_url: 'https://api.github.com/repos/twbs/bootstrap/hooks',
      issue_events_url: 'https://api.github.com/repos/twbs/bootstrap/issues/events{/number}',
      events_url: 'https://api.github.com/repos/twbs/bootstrap/events',
      assignees_url: 'https://api.github.com/repos/twbs/bootstrap/assignees{/user}',
      branches_url: 'https://api.github.com/repos/twbs/bootstrap/branches{/branch}',
      tags_url: 'https://api.github.com/repos/twbs/bootstrap/tags',
      blobs_url: 'https://api.github.com/repos/twbs/bootstrap/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/twbs/bootstrap/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/twbs/bootstrap/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/twbs/bootstrap/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/twbs/bootstrap/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/twbs/bootstrap/languages',
      stargazers_url: 'https://api.github.com/repos/twbs/bootstrap/stargazers',
      contributors_url: 'https://api.github.com/repos/twbs/bootstrap/contributors',
      subscribers_url: 'https://api.github.com/repos/twbs/bootstrap/subscribers',
      subscription_url: 'https://api.github.com/repos/twbs/bootstrap/subscription',
      commits_url: 'https://api.github.com/repos/twbs/bootstrap/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/twbs/bootstrap/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/twbs/bootstrap/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/twbs/bootstrap/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/twbs/bootstrap/contents/{+path}',
      compare_url: 'https://api.github.com/repos/twbs/bootstrap/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/twbs/bootstrap/merges',
      archive_url: 'https://api.github.com/repos/twbs/bootstrap/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/twbs/bootstrap/downloads',
      issues_url: 'https://api.github.com/repos/twbs/bootstrap/issues{/number}',
      pulls_url: 'https://api.github.com/repos/twbs/bootstrap/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/twbs/bootstrap/milestones{/number}',
      notifications_url:
        'https://api.github.com/repos/twbs/bootstrap/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/twbs/bootstrap/labels{/name}',
      releases_url: 'https://api.github.com/repos/twbs/bootstrap/releases{/id}',
      deployments_url: 'https://api.github.com/repos/twbs/bootstrap/deployments',
      created_at: '2011-07-29T21:19:00Z',
      updated_at: '2024-07-10T14:35:55Z',
      pushed_at: '2024-07-10T15:14:25Z',
      git_url: 'git://github.com/twbs/bootstrap.git',
      ssh_url: 'git@github.com:twbs/bootstrap.git',
      clone_url: 'https://github.com/twbs/bootstrap.git',
      svn_url: 'https://github.com/twbs/bootstrap',
      homepage: 'https://getbootstrap.com',
      size: 262284,
      stargazers_count: 168067,
      watchers_count: 168067,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: false,
      has_pages: true,
      has_discussions: true,
      forks_count: 78548,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 578,
      license: {
        key: 'mit',
        name: 'MIT License',
        spdx_id: 'MIT',
        url: 'https://api.github.com/licenses/mit',
        node_id: 'MDc6TGljZW5zZTEz'
      },
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: ['bootstrap', 'css', 'css-framework', 'html', 'javascript', 'sass', 'scss'],
      visibility: 'public',
      forks: 78548,
      open_issues: 578,
      watchers: 168067,
      default_branch: 'main',
      permissions: {
        admin: false,
        maintain: false,
        push: false,
        triage: false,
        pull: true
      },
      temp_clone_token: '',
      custom_properties: {},
      organization: {
        login: 'twbs',
        id: 2918581,
        node_id: 'MDEyOk9yZ2FuaXphdGlvbjI5MTg1ODE=',
        avatar_url: 'https://avatars.githubusercontent.com/u/2918581?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/twbs',
        html_url: 'https://github.com/twbs',
        followers_url: 'https://api.github.com/users/twbs/followers',
        following_url: 'https://api.github.com/users/twbs/following{/other_user}',
        gists_url: 'https://api.github.com/users/twbs/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/twbs/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/twbs/subscriptions',
        organizations_url: 'https://api.github.com/users/twbs/orgs',
        repos_url: 'https://api.github.com/users/twbs/repos',
        events_url: 'https://api.github.com/users/twbs/events{/privacy}',
        received_events_url: 'https://api.github.com/users/twbs/received_events',
        type: 'Organization',
        site_admin: false
      },
      network_count: 78548,
      subscribers_count: 6748
    };

    expect(repositorySchema.parse(repository)).toEqual({
      id: 2126244,
      node_id: 'MDEwOlJlcG9zaXRvcnkyMTI2MjQ0',
      name: 'bootstrap',
      full_name: 'twbs/bootstrap',
      private: false,
      owner: expect.objectContaining({ login: 'twbs', id: 2918581 }),
      description:
        'The most popular HTML, CSS, and JavaScript framework for developing responsive, mobile first projects on the web.',
      fork: false,
      url: 'https://api.github.com/repos/twbs/bootstrap',
      created_at: new Date('2011-07-29T21:19:00Z'),
      updated_at: new Date('2024-07-10T14:35:55Z'),
      pushed_at: new Date('2024-07-10T15:14:25Z'),
      homepage: 'https://getbootstrap.com',
      size: 262284,
      stargazers_count: 168067,
      watchers_count: 168067,
      language: 'JavaScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: false,
      has_pages: true,
      has_discussions: true,
      forks_count: 78548,
      archived: false,
      disabled: false,
      open_issues_count: 578,
      license: 'mit',
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: ['bootstrap', 'css', 'css-framework', 'html', 'javascript', 'sass', 'scss'],
      visibility: 'public',
      forks: 78548,
      open_issues: 578,
      watchers: 168067,
      default_branch: 'main',
      organization: expect.objectContaining({ login: 'twbs', id: 2918581 }),
      network_count: 78548,
      subscribers_count: 6748,
      __typename: 'Repository',
      __obtained_at: expect.any(Date)
    });
  });
});
